### PR TITLE
[#2] Added MVP Scope

### LINKED ISSUE #2: Scope out MVP
Scope out the general idea of the application and define what we wish to launch with

### PR DESCRIPTION
**Pull request by Puffycheeses**
Added base MVP Scope document. Resolves #2

### CODE REVIEW

**Comment by jchamnankool** [comment]
This is an empty file.

**Comment by Puffycheeses** [comment]
My bad!

**Review by jchamnankool — CHANGES_REQUESTED** [review]
Maybe add a function to visually warn the user if there is a long wait (>15mins) for a game, i.e. a red alert symbol for maimai.

**Comment by Puffycheeses** [comment]
> 
> 
> Maybe add a function to visually warn the user if there is a long wait (>15mins) for a game, i.e. a red alert symbol for maimai.

That's a pretty good idea, I'll add it under the queue heading!

**Review by jchamnankool — APPROVED** [review]
Nice!

**Pull request merged**
